language: ruby
install: bundle install --jobs=3 --retry=3
script: bundle exec rspec

sudo: false

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
#  - rbx-2
notifications:
  email: false
matrix:
  fast_finish: true
