require 'spec_helper'

# from http://www.theguardian.com/books/list/authorsaz
# { from: "Brooke Magnanti (Belle de Jour)", to: { full: "Brooke Magnanti (Belle de Jour)", first: "Brooke Magnanti (Belle de", last: "Jour)" } },
# { from: "Saki (Hector Hugh Munro)", to: { full: "Saki (Hector Hugh Munro)", first: "Saki (Hector Hugh", last: "Munro)" } },
# { from: "Steven D Levitt and Stephen J Dubner", to: { full: "Steven D Levitt and Stephen J Dubner", first: "Steven D Levitt and Stephen J", last: "Dubner" } },

RSpec.describe "The Guardian author list" do
  context "with the names" do
    [
      { from: "Chinua Achebe", to: { full: "Chinua Achebe", first: "Chinua", last: "Achebe" } },
      { from: "Peter Ackroyd", to: { full: "Peter Ackroyd", first: "Peter", last: "Ackroyd" } },
      { from: "Douglas Adams", to: { full: "Douglas Adams", first: "Douglas", last: "Adams" } },
      { from: "Chimamanda Ngozi Adichie", to: { full: "Chimamanda Ngozi Adichie", first: "Chimamanda Ngozi", last: "Adichie" } },
      { from: "Aaron Akinyemi", to: { full: "Aaron Akinyemi", first: "Aaron", last: "Akinyemi" } },
      { from: "Alexandra Harris", to: { full: "Alexandra Harris", first: "Alexandra", last: "Harris" } },
      { from: "Monica Ali", to: { full: "Monica Ali", first: "Monica", last: "Ali" } },
      { from: "Dante Alighieri", to: { full: "Dante Alighieri", first: "Dante", last: "Alighieri" } },
      { from: "Alistair Cooke", to: { full: "Alistair Cooke", first: "Alistair", last: "Cooke" } },
      { from: "Isabel Allende", to: { full: "Isabel Allende", first: "Isabel", last: "Allende" } },
      { from: "Kingsley Amis", to: { full: "Kingsley Amis", first: "Kingsley", last: "Amis" } },
      { from: "Martin Amis", to: { full: "Martin Amis", first: "Martin", last: "Amis" } },
      { from: "Maya Angelou", to: { full: "Maya Angelou", first: "Maya", last: "Angelou" } },
      { from: "Annie Proulx", to: { full: "Annie Proulx", first: "Annie", last: "Proulx" } },
      { from: "Jeffrey Archer", to: { full: "Jeffrey Archer", first: "Jeffrey", last: "Archer" } },
      { from: "Philip Ardagh", to: { full: "Philip Ardagh", first: "Philip", last: "Ardagh" } },
      { from: "Simon Armitage", to: { full: "Simon Armitage", first: "Simon", last: "Armitage" } },
      { from: "Isaac Asimov", to: { full: "Isaac Asimov", first: "Isaac", last: "Asimov" } },
      { from: "Åsne Seierstad", to: { full: "Åsne Seierstad", first: "Åsne", last: "Seierstad" } },
      { from: "Diana Athill", to: { full: "Diana Athill", first: "Diana", last: "Athill" } },
      { from: "Kate Atkinson", to: { full: "Kate Atkinson", first: "Kate", last: "Atkinson" } },
      { from: "Margaret Atwood", to: { full: "Margaret Atwood", first: "Margaret", last: "Atwood" } },
      { from: "WH Auden", to: { full: "WH Auden", first: "WH", last: "Auden" } },
      { from: "Jane Austen", to: { full: "Jane Austen", first: "Jane", last: "Austen" } },
      { from: "Paul Auster", to: { full: "Paul Auster", first: "Paul", last: "Auster" } },

      { from: "Julian Baggini", to: { full: "Julian Baggini", first: "Julian", last: "Baggini" } },
      { from: "Paul Bailey", to: { full: "Paul Bailey", first: "Paul", last: "Bailey" } },
      { from: "Beryl Bainbridge", to: { full: "Beryl Bainbridge", first: "Beryl", last: "Bainbridge" } },
      { from: "James Baldwin", to: { full: "James Baldwin", first: "James", last: "Baldwin" } },
      { from: "JG Ballard", to: { full: "JG Ballard", first: "JG", last: "Ballard" } },
      { from: "Iain Banks", to: { full: "Iain Banks", first: "Iain", last: "Banks" } },
      { from: "John Banville", to: { full: "John Banville", first: "John", last: "Banville" } },
      { from: "Clive Barker", to: { full: "Clive Barker", first: "Clive", last: "Barker" } },
      { from: "Pat Barker", to: { full: "Pat Barker", first: "Pat", last: "Barker" } },
      { from: "Nicola Barker", to: { full: "Nicola Barker", first: "Nicola", last: "Barker" } },
      { from: "Julian Barnes", to: { full: "Julian Barnes", first: "Julian", last: "Barnes" } },
      { from: "Sebastian Barry", to: { full: "Sebastian Barry", first: "Sebastian", last: "Barry" } },
      { from: "Donald Barthelme", to: { full: "Donald Barthelme", first: "Donald", last: "Barthelme" } },
      { from: "Belinda Bauer", to: { full: "Belinda Bauer", first: "Belinda", last: "Bauer" } },
      { from: "Nina Bawden", to: { full: "Nina Bawden", first: "Nina", last: "Bawden" } },
      { from: "Mary Beard", to: { full: "Mary Beard", first: "Mary", last: "Beard" } },
      { from: "Simone de Beauvoir", to: { full: "Simone de Beauvoir", first: "Simone", last: "de Beauvoir" } },
      { from: "Samuel Beckett", to: { full: "Samuel Beckett", first: "Samuel", last: "Beckett" } },
      { from: "Antony Beevor", to: { full: "Antony Beevor", first: "Antony", last: "Beevor" } },
      { from: "Saul Bellow", to: { full: "Saul Bellow", first: "Saul", last: "Bellow" } },
      { from: "Benjamin Markovits", to: { full: "Benjamin Markovits", first: "Benjamin", last: "Markovits" } },
      { from: "George Bernard Shaw", to: { full: "George Bernard Shaw", first: "George Bernard", last: "Shaw" } },
      { from: "Louis de Bernières", to: { full: "Louis de Bernières", first: "Louis", last: "de Bernières" } },
      { from: "John Betjeman", to: { full: "John Betjeman", first: "John", last: "Betjeman" } },
      { from: "Maeve Binchy", to: { full: "Maeve Binchy", first: "Maeve", last: "Binchy" } },
      { from: "Carol Birch", to: { full: "Carol Birch", first: "Carol", last: "Birch" } },
      { from: "Quentin Blake", to: { full: "Quentin Blake", first: "Quentin", last: "Blake" } },
      { from: "William Blake", to: { full: "William Blake", first: "William", last: "Blake" } },
      { from: "Enid Blyton", to: { full: "Enid Blyton", first: "Enid", last: "Blyton" } },
      { from: "Roberto Bolaño", to: { full: "Roberto Bolaño", first: "Roberto", last: "Bolaño" } },
      { from: "Katherine Boo", to: { full: "Katherine Boo", first: "Katherine", last: "Boo" } },
      { from: "Jorge Luis Borges", to: { full: "Jorge Luis Borges", first: "Jorge Luis", last: "Borges" } },
      { from: "William Boyd", to: { full: "William Boyd", first: "William", last: "Boyd" } },
      { from: "Ray Bradbury", to: { full: "Ray Bradbury", first: "Ray", last: "Bradbury" } },
      { from: "Barbara Taylor Bradford", to: { full: "Barbara Taylor Bradford", first: "Barbara Taylor", last: "Bradford" } },
      { from: "Stewart Brand", to: { full: "Stewart Brand", first: "Stewart", last: "Brand" } },
      { from: "Raymond Briggs", to: { full: "Raymond Briggs", first: "Raymond", last: "Briggs" } },
      { from: "Constance Briscoe", to: { full: "Constance Briscoe", first: "Constance", last: "Briscoe" } },
      { from: "Anne Brontë", to: { full: "Anne Brontë", first: "Anne", last: "Brontë" } },
      { from: "Charlotte Brontë", to: { full: "Charlotte Brontë", first: "Charlotte", last: "Brontë" } },
      { from: "Emily Brontë", to: { full: "Emily Brontë", first: "Emily", last: "Brontë" } },
      { from: "Anita Brookner", to: { full: "Anita Brookner", first: "Anita", last: "Brookner" } },
      { from: "Dan Brown", to: { full: "Dan Brown", first: "Dan", last: "Brown" } },
      { from: "Jeffrey Brown", to: { full: "Jeffrey Brown", first: "Jeffrey", last: "Brown" } },
      { from: "Anthony Browne", to: { full: "Anthony Browne", first: "Anthony", last: "Browne" } },
      { from: "Bill Bryson", to: { full: "Bill Bryson", first: "Bill", last: "Bryson" } },
      { from: "Mikhail Bulgakov", to: { full: "Mikhail Bulgakov", first: "Mikhail", last: "Bulgakov" } },
      { from: "Anthony Burgess", to: { full: "Anthony Burgess", first: "Anthony", last: "Burgess" } },
      { from: "Melvin Burgess", to: { full: "Melvin Burgess", first: "Melvin", last: "Burgess" } },
      { from: "Gordon Burn", to: { full: "Gordon Burn", first: "Gordon", last: "Burn" } },
      { from: "Robert Burns", to: { full: "Robert Burns", first: "Robert", last: "Burns" } },
      { from: "William Burroughs", to: { full: "William Burroughs", first: "William", last: "Burroughs" } },
      { from: "AS Byatt", to: { full: "AS Byatt", first: "AS", last: "Byatt" } },
      { from: "Lord Byron", to: { full: "Lord Byron", first: "Lord", last: "Byron" } },

      { from: "Carmen Callil", to: { full: "Carmen Callil", first: "Carmen", last: "Callil" } },
      { from: "Italo Calvino", to: { full: "Italo Calvino", first: "Italo", last: "Calvino" } },
      { from: "Albert Camus", to: { full: "Albert Camus", first: "Albert", last: "Camus" } },
      { from: "Truman Capote", to: { full: "Truman Capote", first: "Truman", last: "Capote" } },
      { from: "Peter Carey", to: { full: "Peter Carey", first: "Peter", last: "Carey" } },
      { from: "Carlos Fuentes", to: { full: "Carlos Fuentes", first: "Carlos", last: "Fuentes" } },
      { from: "Lewis Carroll", to: { full: "Lewis Carroll", first: "Lewis", last: "Carroll" } },
      { from: "Angela Carter", to: { full: "Angela Carter", first: "Angela", last: "Carter" } },
      { from: "Raymond Carver", to: { full: "Raymond Carver", first: "Raymond", last: "Carver" } },
      { from: "Eleanor Catton", to: { full: "Eleanor Catton", first: "Eleanor", last: "Catton" } },
      { from: "Miguel de Cervantes", to: { full: "Miguel de Cervantes", first: "Miguel", last: "de Cervantes" } },
      { from: "Michael Chabon", to: { full: "Michael Chabon", first: "Michael", last: "Chabon" } },
      { from: "Raymond Chandler", to: { full: "Raymond Chandler", first: "Raymond", last: "Chandler" } },
      { from: "Rajiv Chandrasekaran", to: { full: "Rajiv Chandrasekaran", first: "Rajiv", last: "Chandrasekaran" } },
      { from: "Bruce Chatwin", to: { full: "Bruce Chatwin", first: "Bruce", last: "Chatwin" } },
      { from: "Geoffrey Chaucer", to: { full: "Geoffrey Chaucer", first: "Geoffrey", last: "Chaucer" } },
      { from: "Anton Chekhov", to: { full: "Anton Chekhov", first: "Anton", last: "Chekhov" } },
      { from: "GK Chesterton", to: { full: "GK Chesterton", first: "GK", last: "Chesterton" } },
      { from: "Lauren Child", to: { full: "Lauren Child", first: "Lauren", last: "Child" } },
      { from: "Chris Ware", to: { full: "Chris Ware", first: "Chris", last: "Ware" } },
      { from: "Agatha Christie", to: { full: "Agatha Christie", first: "Agatha", last: "Christie" } },
      { from: "Christopher Isherwood", to: { full: "Christopher Isherwood", first: "Christopher", last: "Isherwood" } },
      { from: "CJ Sansom", to: { full: "CJ Sansom", first: "CJ", last: "Sansom" } },
      { from: "Tom Clancy", to: { full: "Tom Clancy", first: "Tom", last: "Clancy" } },
      { from: "John Clare", to: { full: "John Clare", first: "John", last: "Clare" } },
      { from: "Arthur C Clarke", to: { full: "Arthur C Clarke", first: "Arthur C", last: "Clarke" } },
      { from: "John Cooper Clarke", to: { full: "John Cooper Clarke", first: "John Cooper", last: "Clarke" } },
      { from: "Daniel Clowes", to: { full: "Daniel Clowes", first: "Daniel", last: "Clowes" } },
      { from: "Jonathan Coe", to: { full: "Jonathan Coe", first: "Jonathan", last: "Coe" } },
      { from: "Paulo Coelho", to: { full: "Paulo Coelho", first: "Paulo", last: "Coelho" } },
      { from: "JM Coetzee", to: { full: "JM Coetzee", first: "JM", last: "Coetzee" } },
      { from: "Samuel Taylor Coleridge", to: { full: "Samuel Taylor Coleridge", first: "Samuel Taylor", last: "Coleridge" } },
      { from: "Eoin Colfer", to: { full: "Eoin Colfer", first: "Eoin", last: "Colfer" } },
      { from: "Wilkie Collins", to: { full: "Wilkie Collins", first: "Wilkie", last: "Collins" } },
      { from: "Jackie Collins", to: { full: "Jackie Collins", first: "Jackie", last: "Collins" } },
      { from: "Colum McCann", to: { full: "Colum McCann", first: "Colum", last: "McCann" } },
      { from: "Arthur Conan Doyle", to: { full: "Arthur Conan Doyle", first: "Arthur Conan", last: "Doyle" } },
      { from: "Joseph Connolly", to: { full: "Joseph Connolly", first: "Joseph", last: "Connolly" } },
      { from: "Joseph Conrad", to: { full: "Joseph Conrad", first: "Joseph", last: "Conrad" } },
      { from: "Jilly Cooper", to: { full: "Jilly Cooper", first: "Jilly", last: "Cooper" } },
      { from: "Patricia Cornwell", to: { full: "Patricia Cornwell", first: "Patricia", last: "Cornwell" } },
      { from: "Douglas Coupland", to: { full: "Douglas Coupland", first: "Douglas", last: "Coupland" } },
      { from: "Jim Crace", to: { full: "Jim Crace", first: "Jim", last: "Crace" } },
      { from: "Michael Crichton", to: { full: "Michael Crichton", first: "Michael", last: "Crichton" } },
      { from: "Neil Cross", to: { full: "Neil Cross", first: "Neil", last: "Cross" } },
      { from: "Robert Crumb", to: { full: "Robert Crumb", first: "Robert", last: "Crumb" } },
      { from: "Curtis Sittenfeld", to: { full: "Curtis Sittenfeld", first: "Curtis", last: "Sittenfeld" } },
      { from: "Czesław Miłosz", to: { full: "Czesław Miłosz", first: "Czesław", last: "Miłosz" } },

      { from: "Roald Dahl", to: { full: "Roald Dahl", first: "Roald", last: "Dahl" } },
      { from: "David Sedaris", to: { full: "David Sedaris", first: "David", last: "Sedaris" } },
      { from: "DBC Pierre", to: { full: "DBC Pierre", first: "DBC", last: "Pierre" } },
      { from: "Edmund de Waal", to: { full: "Edmund de Waal", first: "Edmund", last: "de Waal" } },
      { from: "Daniel Defoe", to: { full: "Daniel Defoe", first: "Daniel", last: "Defoe" } },
      { from: "Len Deighton", to: { full: "Len Deighton", first: "Len", last: "Deighton" } },
      { from: "Don DeLillo", to: { full: "Don DeLillo", first: "Don", last: "DeLillo" } },
      { from: "Patrick DeWitt", to: { full: "Patrick DeWitt", first: "Patrick", last: "DeWitt" } },
      { from: "Giuseppe Tomasi di Lampedusa", to: { full: "Giuseppe Tomasi di Lampedusa", first: "Giuseppe Tomasi", last: "di Lampedusa" } },
      { from: "Junot Diaz", to: { full: "Junot Diaz", first: "Junot", last: "Diaz" } },
      { from: "Philip K Dick", to: { full: "Philip K Dick", first: "Philip K", last: "Dick" } },
      { from: "Dick King-Smith", to: { full: "Dick King-Smith", first: "Dick", last: "King-Smith" } },
      { from: "Charles Dickens", to: { full: "Charles Dickens", first: "Charles", last: "Dickens" } },
      { from: "Emily Dickinson", to: { full: "Emily Dickinson", first: "Emily", last: "Dickinson" } },
      { from: "Don Paterson", to: { full: "Don Paterson", first: "Don", last: "Paterson" } },
      { from: "Emma Donoghue", to: { full: "Emma Donoghue", first: "Emma", last: "Donoghue" } },
      { from: "Fyodor Dostoevsky", to: { full: "Fyodor Dostoevsky", first: "Fyodor", last: "Dostoevsky" } },
      { from: "Roddy Doyle", to: { full: "Roddy Doyle", first: "Roddy", last: "Doyle" } },
      { from: "Margaret Drabble", to: { full: "Margaret Drabble", first: "Margaret", last: "Drabble" } },
      { from: "Carol Ann Duffy", to: { full: "Carol Ann Duffy", first: "Carol Ann", last: "Duffy" } },
      { from: "Alexandre Dumas, pere", to: { full: "Alexandre Dumas", first: "Alexandre", last: "Dumas", suffix: "pere" } },
      { from: "Daphne du Maurier", to: { full: "Daphne du Maurier", first: "Daphne", last: "du Maurier" } },
      { from: "Helen Dunmore", to: { full: "Helen Dunmore", first: "Helen", last: "Dunmore" } },
      { from: "Lawrence Durrell", to: { full: "Lawrence Durrell", first: "Lawrence", last: "Durrell" } },

      { from: "David Eagleman", to: { full: "David Eagleman", first: "David", last: "Eagleman" } },
      { from: "Terry Eagleton", to: { full: "Terry Eagleton", first: "Terry", last: "Eagleton" } },
      { from: "Bret Easton Ellis", to: { full: "Bret Easton Ellis", first: "Bret Easton", last: "Ellis" } },
      { from: "Umberto Eco", to: { full: "Umberto Eco", first: "Umberto", last: "Eco" } },
      { from: "Esi Edugyan", to: { full: "Esi Edugyan", first: "Esi", last: "Edugyan" } },
      { from: "Dave Eggers", to: { full: "Dave Eggers", first: "Dave", last: "Eggers" } },
      { from: "George Eliot", to: { full: "George Eliot", first: "George", last: "Eliot" } },
      { from: "James Ellroy", to: { full: "James Ellroy", first: "James", last: "Ellroy" } },
      { from: "Anne Enright", to: { full: "Anne Enright", first: "Anne", last: "Enright" } },
      { from: "Jeffrey Eugenides", to: { full: "Jeffrey Eugenides", first: "Jeffrey", last: "Eugenides" } },
      { from: "Evie Wyld", to: { full: "Evie Wyld", first: "Evie", last: "Wyld" } },

      { from: "William Faulkner", to: { full: "William Faulkner", first: "William", last: "Faulkner" } },
      { from: "Sebastian Faulks", to: { full: "Sebastian Faulks", first: "Sebastian", last: "Faulks" } },
      { from: "Niall Ferguson", to: { full: "Niall Ferguson", first: "Niall", last: "Ferguson" } },
      { from: "Helen Fielding", to: { full: "Helen Fielding", first: "Helen", last: "Fielding" } },
      { from: "Henry Fielding", to: { full: "Henry Fielding", first: "Henry", last: "Fielding" } },
      { from: "Orlando Figes", to: { full: "Orlando Figes", first: "Orlando", last: "Figes" } },
      { from: "F Scott Fitzgerald", to: { full: "F Scott Fitzgerald", first: "F Scott", last: "Fitzgerald" } },
      { from: "Gustave Flaubert", to: { full: "Gustave Flaubert", first: "Gustave", last: "Flaubert" } },
      { from: "Ian Fleming", to: { full: "Ian Fleming", first: "Ian", last: "Fleming" } },
      { from: "Gillian Flynn", to: { full: "Gillian Flynn", first: "Gillian", last: "Flynn" } },
      { from: "EM Forster", to: { full: "EM Forster", first: "EM", last: "Forster" } },
      { from: "Adam Foulds", to: { full: "Adam Foulds", first: "Adam", last: "Foulds" } },
      { from: "John Fowles", to: { full: "John Fowles", first: "John", last: "Fowles" } },
      { from: "Dick Francis", to: { full: "Dick Francis", first: "Dick", last: "Francis" } },
      { from: "Thomas Frank", to: { full: "Thomas Frank", first: "Thomas", last: "Frank" } },
      { from: "Jonathan Franzen", to: { full: "Jonathan Franzen", first: "Jonathan", last: "Franzen" } },
      { from: "Nicci French", to: { full: "Nicci French", first: "Nicci", last: "French" } },
      { from: "Tana French", to: { full: "Tana French", first: "Tana", last: "French" } },
      { from: "Sigmund Freud", to: { full: "Sigmund Freud", first: "Sigmund", last: "Freud" } },
      { from: "Nell Freudenberger", to: { full: "Nell Freudenberger", first: "Nell", last: "Freudenberger" } },
      { from: "James Frey", to: { full: "James Frey", first: "James", last: "Frey" } },
      { from: "Francis Fukuyama", to: { full: "Francis Fukuyama", first: "Francis", last: "Fukuyama" } },

      { from: "G Willow Wilson", to: { full: "G Willow Wilson", first: "G Willow", last: "Wilson" } },
      { from: "Neil Gaiman", to: { full: "Neil Gaiman", first: "Neil", last: "Gaiman" } },
      { from: "Damon Galgut", to: { full: "Damon Galgut", first: "Damon", last: "Galgut" } },
      { from: "Petina Gappah", to: { full: "Petina Gappah", first: "Petina", last: "Gappah" } },
      { from: "Simon Garfield", to: { full: "Simon Garfield", first: "Simon", last: "Garfield" } },
      { from: "Alan Garner", to: { full: "Alan Garner", first: "Alan", last: "Garner" } },
      { from: "William Gibson", to: { full: "William Gibson", first: "William", last: "Gibson" } },
      { from: "Martin Gilbert", to: { full: "Martin Gilbert", first: "Martin", last: "Gilbert" } },
      { from: "Allen Ginsberg", to: { full: "Allen Ginsberg", first: "Allen", last: "Ginsberg" } },
      { from: "Malcolm Gladwell", to: { full: "Malcolm Gladwell", first: "Malcolm", last: "Gladwell" } },
      { from: "Nikolai Gogol", to: { full: "Nikolai Gogol", first: "Nikolai", last: "Gogol" } },
      { from: "Glen David Gold", to: { full: "Glen David Gold", first: "Glen David", last: "Gold" } },
      { from: "William Golding", to: { full: "William Golding", first: "William", last: "Golding" } },
      { from: "Nadine Gordimer", to: { full: "Nadine Gordimer", first: "Nadine", last: "Gordimer" } },
      { from: "Gore Vidal", to: { full: "Gore Vidal", first: "Gore", last: "Vidal" } },
      { from: "Günter Grass", to: { full: "Günter Grass", first: "Günter", last: "Grass" } },
      { from: "Alasdair Gray", to: { full: "Alasdair Gray", first: "Alasdair", last: "Gray" } },
      { from: "Simon Gray", to: { full: "Simon Gray", first: "Simon", last: "Gray" } },
      { from: "John Green", to: { full: "John Green", first: "John", last: "Green" } },
      { from: "Graham Greene", to: { full: "Graham Greene", first: "Graham", last: "Greene" } },
      { from: "Germaine Greer", to: { full: "Germaine Greer", first: "Germaine", last: "Greer" } },
      { from: "Philippa Gregory", to: { full: "Philippa Gregory", first: "Philippa", last: "Gregory" } },
      { from: "John Grisham", to: { full: "John Grisham", first: "John", last: "Grisham" } },
      { from: "David Grossman", to: { full: "David Grossman", first: "David", last: "Grossman" } },

      { from: "Mark Haddon", to: { full: "Mark Haddon", first: "Mark", last: "Haddon" } },
      { from: "Tessa Hadley", to: { full: "Tessa Hadley", first: "Tessa", last: "Hadley" } },
      { from: "Knut Hamsun", to: { full: "Knut Hamsun", first: "Knut", last: "Hamsun" } },
      { from: "Mohammed Hanif", to: { full: "Mohammed Hanif", first: "Mohammed", last: "Hanif" } },
      { from: "Elizabeth Hardwick", to: { full: "Elizabeth Hardwick", first: "Elizabeth", last: "Hardwick" } },
      { from: "Thomas Hardy", to: { full: "Thomas Hardy", first: "Thomas", last: "Hardy" } },
      { from: "Thomas Harris", to: { full: "Thomas Harris", first: "Thomas", last: "Harris" } },
      { from: "Robert Harris", to: { full: "Robert Harris", first: "Robert", last: "Harris" } },
      { from: "Tony Harrison", to: { full: "Tony Harrison", first: "Tony", last: "Harrison" } },
      { from: "David Harsent", to: { full: "David Harsent", first: "David", last: "Harsent" } },
      { from: "Josephine Hart", to: { full: "Josephine Hart", first: "Josephine", last: "Hart" } },
      { from: "Seamus Heaney", to: { full: "Seamus Heaney", first: "Seamus", last: "Heaney" } },
      { from: "Helen Simpson", to: { full: "Helen Simpson", first: "Helen", last: "Simpson" } },
      { from: "Joseph Heller", to: { full: "Joseph Heller", first: "Joseph", last: "Heller" } },
      { from: "Ernest Hemingway", to: { full: "Ernest Hemingway", first: "Ernest", last: "Hemingway" } },
      { from: "Aleksandar Hemon", to: { full: "Aleksandar Hemon", first: "Aleksandar", last: "Hemon" } },
      { from: "James Herbert", to: { full: "James Herbert", first: "James", last: "Herbert" } },
      { from: "Herta Müller", to: { full: "Herta Müller", first: "Herta", last: "Müller" } },
      { from: "Georgette Heyer", to: { full: "Georgette Heyer", first: "Georgette", last: "Heyer" } },
      { from: "Carl Hiaasen", to: { full: "Carl Hiaasen", first: "Carl", last: "Hiaasen" } },
      { from: "Charlie Higson", to: { full: "Charlie Higson", first: "Charlie", last: "Higson" } },
      { from: "Tobias Hill", to: { full: "Tobias Hill", first: "Tobias", last: "Hill" } },
      { from: "Peter Hitchens", to: { full: "Peter Hitchens", first: "Peter", last: "Hitchens" } },
      { from: "Christopher Hitchens", to: { full: "Christopher Hitchens", first: "Christopher", last: "Hitchens" } },
      { from: "Shere Hite", to: { full: "Shere Hite", first: "Shere", last: "Hite" } },
      { from: "Eric Hobsbawm", to: { full: "Eric Hobsbawm", first: "Eric", last: "Hobsbawm" } },
      { from: "Alan Hollinghurst", to: { full: "Alan Hollinghurst", first: "Alan", last: "Hollinghurst" } },
      { from: "Holly Black", to: { full: "Holly Black", first: "Holly", last: "Black" } },
      { from: "Richard Holmes", to: { full: "Richard Holmes", first: "Richard", last: "Holmes" } },

      { from: "Chloe Hooper", to: { full: "Chloe Hooper", first: "Chloe", last: "Hooper" } },
      { from: "Nick Hornby", to: { full: "Nick Hornby", first: "Nick", last: "Hornby" } },
      { from: "Anthony Horowitz", to: { full: "Anthony Horowitz", first: "Anthony", last: "Horowitz" } },
      { from: "Michel Houellebecq", to: { full: "Michel Houellebecq", first: "Michel", last: "Houellebecq" } },
      { from: "Elizabeth Jane Howard", to: { full: "Elizabeth Jane Howard", first: "Elizabeth Jane", last: "Howard" } },
      { from: "Ted Hughes", to: { full: "Ted Hughes", first: "Ted", last: "Hughes" } },
      { from: "Shirley Hughes", to: { full: "Shirley Hughes", first: "Shirley", last: "Hughes" } },
      { from: "Siri Hustvedt", to: { full: "Siri Hustvedt", first: "Siri", last: "Hustvedt" } },
      { from: "Aldous Huxley", to: { full: "Aldous Huxley", first: "Aldous", last: "Huxley" } },

      { from: "Eva Ibbotson", to: { full: "Eva Ibbotson", first: "Eva", last: "Ibbotson" } },
      { from: "Henrik Ibsen", to: { full: "Henrik Ibsen", first: "Henrik", last: "Ibsen" } },
      { from: "Mick Imlah", to: { full: "Mick Imlah", first: "Mick", last: "Imlah" } },
      { from: "John Irving", to: { full: "John Irving", first: "John", last: "Irving" } },
      { from: "Kazuo Ishiguro", to: { full: "Kazuo Ishiguro", first: "Kazuo", last: "Ishiguro" } },

      { from: "Jackie Morris", to: { full: "Jackie Morris", first: "Jackie", last: "Morris" } },
      { from: "Howard Jacobson", to: { full: "Howard Jacobson", first: "Howard", last: "Jacobson" } },
      { from: "Henry James", to: { full: "Henry James", first: "Henry", last: "James" } },
      { from: "EL James", to: { full: "EL James", first: "EL", last: "James" } },
      { from: "PD James", to: { full: "PD James", first: "PD", last: "James" } },
      { from: "Jay McInerney", to: { full: "Jay McInerney", first: "Jay", last: "McInerney" } },
      { from: "Jo Nesbø", to: { full: "Jo Nesbø", first: "Jo", last: "Nesbø" } },
      { from: "Joanna Kavenna", to: { full: "Joanna Kavenna", first: "Joanna", last: "Kavenna" } },
      { from: "John Cheever", to: { full: "John Cheever", first: "John", last: "Cheever" } },
      { from: "John Gray", to: { full: "John Gray", first: "John", last: "Gray" } },
      { from: "Samuel Johnson", to: { full: "Samuel Johnson", first: "Samuel", last: "Johnson" } },
      { from: "Sadie Jones", to: { full: "Sadie Jones", first: "Sadie", last: "Jones" } },
      { from: "Ben Jonson", to: { full: "Ben Jonson", first: "Ben", last: "Jonson" } },
      { from: "James Joyce", to: { full: "James Joyce", first: "James", last: "Joyce" } },
      { from: "Juan Gabriel Vásquez", to: { full: "Juan Gabriel Vásquez", first: "Juan Gabriel", last: "Vásquez" } },
      { from: "Tony Judt", to: { full: "Tony Judt", first: "Tony", last: "Judt" } },

      { from: "Ismail Kadare", to: { full: "Ismail Kadare", first: "Ismail", last: "Kadare" } },
      { from: "Franz Kafka", to: { full: "Franz Kafka", first: "Franz", last: "Kafka" } },
      { from: "Ryszard Kapuściński", to: { full: "Ryszard Kapuściński", first: "Ryszard", last: "Kapuściński" } },
      { from: "Kathryn Schulz", to: { full: "Kathryn Schulz", first: "Kathryn", last: "Schulz" } },
      { from: "Jackie Kay", to: { full: "Jackie Kay", first: "Jackie", last: "Kay" } },
      { from: "John Keats", to: { full: "John Keats", first: "John", last: "Keats" } },
      { from: "James Kelman", to: { full: "James Kelman", first: "James", last: "Kelman" } },
      { from: "Stephen Kelman", to: { full: "Stephen Kelman", first: "Stephen", last: "Kelman" } },
      { from: "Ken Follett", to: { full: "Ken Follett", first: "Ken", last: "Follett" } },
      { from: "Thomas Keneally", to: { full: "Thomas Keneally", first: "Thomas", last: "Keneally" } },
      { from: "AL Kennedy", to: { full: "AL Kennedy", first: "AL", last: "Kennedy" } },
      { from: "Frank Kermode", to: { full: "Frank Kermode", first: "Frank", last: "Kermode" } },
      { from: "Jack Kerouac", to: { full: "Jack Kerouac", first: "Jack", last: "Kerouac" } },
      { from: "Marian Keyes", to: { full: "Marian Keyes", first: "Marian", last: "Keyes" } },
      { from: "Stephen King", to: { full: "Stephen King", first: "Stephen", last: "King" } },
      { from: "Barbara Kingsolver", to: { full: "Barbara Kingsolver", first: "Barbara", last: "Kingsolver" } },
      { from: "Jeff Kinney", to: { full: "Jeff Kinney", first: "Jeff", last: "Kinney" } },
      { from: "Rudyard Kipling", to: { full: "Rudyard Kipling", first: "Rudyard", last: "Kipling" } },
      { from: "Kiran Desai", to: { full: "Kiran Desai", first: "Kiran", last: "Desai" } },
      { from: "Arthur Koestler", to: { full: "Arthur Koestler", first: "Arthur", last: "Koestler" } },
      { from: "Milan Kundera", to: { full: "Milan Kundera", first: "Milan", last: "Kundera" } },
      { from: "Hanif Kureishi", to: { full: "Hanif Kureishi", first: "Hanif", last: "Kureishi" } },
      { from: "Mark Kurlansky", to: { full: "Mark Kurlansky", first: "Mark", last: "Kurlansky" } },
      { from: "Tony Kushner", to: { full: "Tony Kushner", first: "Tony", last: "Kushner" } },

      { from: "Jhumpa Lahiri", to: { full: "Jhumpa Lahiri", first: "Jhumpa", last: "Lahiri" } },
      { from: "RD Laing", to: { full: "RD Laing", first: "RD", last: "Laing" } },
      { from: "Philip Larkin", to: { full: "Philip Larkin", first: "Philip", last: "Larkin" } },
      { from: "Stieg Larsson", to: { full: "Stieg Larsson", first: "Stieg", last: "Larsson" } },
      { from: "DH Lawrence", to: { full: "DH Lawrence", first: "DH", last: "Lawrence" } },
      { from: "John le Carré", to: { full: "John le Carré", first: "John", last: "le Carré" } },
      { from: "Darian Leader", to: { full: "Darian Leader", first: "Darian", last: "Leader" } },
      { from: "Harper Lee", to: { full: "Harper Lee", first: "Harper", last: "Lee" } },
      { from: "Ursula K Le Guin", to: { full: "Ursula K Le Guin", first: "Ursula K", last: "Le Guin" } },
      { from: "Elmore Leonard", to: { full: "Elmore Leonard", first: "Elmore", last: "Leonard" } },
      { from: "Doris Lessing", to: { full: "Doris Lessing", first: "Doris", last: "Lessing" } },
      { from: "Jonathan Lethem", to: { full: "Jonathan Lethem", first: "Jonathan", last: "Lethem" } },
      { from: "Primo Levi", to: { full: "Primo Levi", first: "Primo", last: "Levi" } },
      { from: "Andrea Levy", to: { full: "Andrea Levy", first: "Andrea", last: "Levy" } },
      { from: "Deborah Levy", to: { full: "Deborah Levy", first: "Deborah", last: "Levy" } },
      { from: "CS Lewis", to: { full: "CS Lewis", first: "CS", last: "Lewis" } },
      { from: "Penelope Lively", to: { full: "Penelope Lively", first: "Penelope", last: "Lively" } },
      { from: "Liz Pichon", to: { full: "Liz Pichon", first: "Liz", last: "Pichon" } },
      { from: "Attica Locke", to: { full: "Attica Locke", first: "Attica", last: "Locke" } },
      { from: "John Locke", to: { full: "John Locke", first: "John", last: "Locke" } },
      { from: "David Lodge", to: { full: "David Lodge", first: "David", last: "Lodge" } },
      { from: "Michael Longley", to: { full: "Michael Longley", first: "Michael", last: "Longley" } },
      { from: "Robert Lowell", to: { full: "Robert Lowell", first: "Robert", last: "Lowell" } },

      { from: "Richard Mabey", to: { full: "Richard Mabey", first: "Richard", last: "Mabey" } },
      { from: "George MacDonald Fraser", to: { full: "George MacDonald Fraser", first: "George MacDonald", last: "Fraser" } },
      { from: "Madeline Miller", to: { full: "Madeline Miller", first: "Madeline", last: "Miller" } },
      { from: "Maggie Gee", to: { full: "Maggie Gee", first: "Maggie", last: "Gee" } },
      { from: "Maile Chapman", to: { full: "Maile Chapman", first: "Maile", last: "Chapman" } },
      { from: "Andrei Makine", to: { full: "Andrei Makine", first: "Andrei", last: "Makine" } },
      { from: "Henning Mankell", to: { full: "Henning Mankell", first: "Henning", last: "Mankell" } },
      { from: "Thomas Mann", to: { full: "Thomas Mann", first: "Thomas", last: "Mann" } },
      { from: "Hilary Mantel", to: { full: "Hilary Mantel", first: "Hilary", last: "Mantel" } },
      { from: "Greil Marcus", to: { full: "Greil Marcus", first: "Greil", last: "Marcus" } },
      { from: "Marcus Sedgwick", to: { full: "Marcus Sedgwick", first: "Marcus", last: "Sedgwick" } },
      { from: "Christopher Marlowe", to: { full: "Christopher Marlowe", first: "Christopher", last: "Marlowe" } },
      { from: "Gabriel García Márquez", to: { full: "Gabriel García Márquez", first: "Gabriel García", last: "Márquez" } },
      { from: "Yann Martel", to: { full: "Yann Martel", first: "Yann", last: "Martel" } },
      { from: "George RR Martin", to: { full: "George RR Martin", first: "George RR", last: "Martin" } },
      { from: "Hisham Matar", to: { full: "Hisham Matar", first: "Hisham", last: "Matar" } },
      { from: "Somerset Maugham", to: { full: "Somerset Maugham", first: "Somerset", last: "Maugham" } },
      { from: "Armistead Maupin", to: { full: "Armistead Maupin", first: "Armistead", last: "Maupin" } },
      { from: "Simon Mawer", to: { full: "Simon Mawer", first: "Simon", last: "Mawer" } },
      { from: "Patrick McCabe", to: { full: "Patrick McCabe", first: "Patrick", last: "McCabe" } },
      { from: "Alexander McCall Smith", to: { full: "Alexander McCall Smith", first: "Alexander McCall", last: "Smith" } },
      { from: "Cormac McCarthy", to: { full: "Cormac McCarthy", first: "Cormac", last: "McCarthy" } },
      { from: "Frank McCourt", to: { full: "Frank McCourt", first: "Frank", last: "McCourt" } },
      { from: "Val McDermid", to: { full: "Val McDermid", first: "Val", last: "McDermid" } },
      { from: "Ian McEwan", to: { full: "Ian McEwan", first: "Ian", last: "McEwan" } },
      { from: "Roger McGough", to: { full: "Roger McGough", first: "Roger", last: "McGough" } },
      { from: "Candia McWilliam", to: { full: "Candia McWilliam", first: "Candia", last: "McWilliam" } },
      { from: "Herman Melville", to: { full: "Herman Melville", first: "Herman", last: "Melville" } },
      { from: "Claire Messud", to: { full: "Claire Messud", first: "Claire", last: "Messud" } },
      { from: "Stephenie Meyer", to: { full: "Stephenie Meyer", first: "Stephenie", last: "Meyer" } },
      { from: "China Miéville", to: { full: "China Miéville", first: "China", last: "Miéville" } },
      { from: "Arthur Miller", to: { full: "Arthur Miller", first: "Arthur", last: "Miller" } },
      { from: "AD Miller", to: { full: "AD Miller", first: "AD", last: "Miller" } },
      { from: "Frank Miller", to: { full: "Frank Miller", first: "Frank", last: "Miller" } },
      { from: "John Milton", to: { full: "John Milton", first: "John", last: "Milton" } },
      { from: "Rohinton Mistry", to: { full: "Rohinton Mistry", first: "Rohinton", last: "Mistry" } },
      { from: "David Mitchell", to: { full: "David Mitchell", first: "David", last: "Mitchell" } },
      { from: "Adrian Mitchell", to: { full: "Adrian Mitchell", first: "Adrian", last: "Mitchell" } },
      { from: "Nancy Mitford", to: { full: "Nancy Mitford", first: "Nancy", last: "Mitford" } },
      { from: "Rutu Modan", to: { full: "Rutu Modan", first: "Rutu", last: "Modan" } },
      { from: "Michel de Montaigne", to: { full: "Michel de Montaigne", first: "Michel", last: "de Montaigne" } },
      { from: "Alan Moore", to: { full: "Alan Moore", first: "Alan", last: "Moore" } },
      { from: "Lisa Moore", to: { full: "Lisa Moore", first: "Lisa", last: "Moore" } },
      { from: "Lorrie Moore", to: { full: "Lorrie Moore", first: "Lorrie", last: "Moore" } },
      { from: "Caitlin Moran", to: { full: "Caitlin Moran", first: "Caitlin", last: "Moran" } },
      { from: "Edwin Morgan", to: { full: "Edwin Morgan", first: "Edwin", last: "Morgan" } },
      { from: "Michael Morpurgo", to: { full: "Michael Morpurgo", first: "Michael", last: "Morpurgo" } },
      { from: "Jan Morris", to: { full: "Jan Morris", first: "Jan", last: "Morris" } },
      { from: "Toni Morrison", to: { full: "Toni Morrison", first: "Toni", last: "Morrison" } },
      { from: "Blake Morrison", to: { full: "Blake Morrison", first: "Blake", last: "Morrison" } },
      { from: "Walter Mosley", to: { full: "Walter Mosley", first: "Walter", last: "Mosley" } },
      { from: "Kate Mosse", to: { full: "Kate Mosse", first: "Kate", last: "Mosse" } },
      { from: "Andrew Motion", to: { full: "Andrew Motion", first: "Andrew", last: "Motion" } },
      { from: "Paul Muldoon", to: { full: "Paul Muldoon", first: "Paul", last: "Muldoon" } },
      { from: "Alice Munro", to: { full: "Alice Munro", first: "Alice", last: "Munro" } },
      { from: "Haruki Murakami", to: { full: "Haruki Murakami", first: "Haruki", last: "Murakami" } },
      { from: "Iris Murdoch", to: { full: "Iris Murdoch", first: "Iris", last: "Murdoch" } },
      { from: "Paul Murray", to: { full: "Paul Murray", first: "Paul", last: "Murray" } },
      { from: "Julie Myerson", to: { full: "Julie Myerson", first: "Julie", last: "Myerson" } },

      { from: "Vladimir Nabokov", to: { full: "Vladimir Nabokov", first: "Vladimir", last: "Nabokov" } },
      { from: "Nadifa Mohamed", to: { full: "Nadifa Mohamed", first: "Nadifa", last: "Mohamed" } },
      { from: "Daljit Nagra", to: { full: "Daljit Nagra", first: "Daljit", last: "Nagra" } },
      { from: "VS Naipaul", to: { full: "VS Naipaul", first: "VS", last: "Naipaul" } },
      { from: "Naomi Klein", to: { full: "Naomi Klein", first: "Naomi", last: "Klein" } },
      { from: "RK Narayan", to: { full: "RK Narayan", first: "RK", last: "Narayan" } },
      { from: "Ned Beauman", to: { full: "Ned Beauman", first: "Ned", last: "Beauman" } },
      { from: "Patrick Ness", to: { full: "Patrick Ness", first: "Patrick", last: "Ness" } },
      { from: "David Nicholls", to: { full: "David Nicholls", first: "David", last: "Nicholls" } },
      { from: "Nick Tosches", to: { full: "Nick Tosches", first: "Nick", last: "Tosches" } },
      { from: "Audrey Niffenegger", to: { full: "Audrey Niffenegger", first: "Audrey", last: "Niffenegger" } },

      { from: "Edna O'Brien", to: { full: "Edna O'Brien", first: "Edna", last: "O'Brien" } },
      { from: "Sean O'Brien", to: { full: "Sean O'Brien", first: "Sean", last: "O'Brien" } },
      { from: "Eugene O'Neill", to: { full: "Eugene O'Neill", first: "Eugene", last: "O'Neill" } },
      { from: "Joyce Carol Oates", to: { full: "Joyce Carol Oates", first: "Joyce Carol", last: "Oates" } },
      { from: "Téa Obreht", to: { full: "Téa Obreht", first: "Téa", last: "Obreht" } },
      { from: "Flann O'Brien", to: { full: "Flann O'Brien", first: "Flann", last: "O'Brien" } },
      { from: "Ben Okri", to: { full: "Ben Okri", first: "Ben", last: "Okri" } },
      { from: "Sharon Olds", to: { full: "Sharon Olds", first: "Sharon", last: "Olds" } },
      { from: "Michael Ondaatje", to: { full: "Michael Ondaatje", first: "Michael", last: "Ondaatje" } },
      { from: "George Orwell", to: { full: "George Orwell", first: "George", last: "Orwell" } },
      { from: "Ruth Ozeki", to: { full: "Ruth Ozeki", first: "Ruth", last: "Ozeki" } },

      { from: "Ruth Padel", to: { full: "Ruth Padel", first: "Ruth", last: "Padel" } },
      { from: "Chuck Palahniuk", to: { full: "Chuck Palahniuk", first: "Chuck", last: "Palahniuk" } },
      { from: "Orhan Pamuk", to: { full: "Orhan Pamuk", first: "Orhan", last: "Pamuk" } },
      { from: "Boris Pasternak", to: { full: "Boris Pasternak", first: "Boris", last: "Pasternak" } },
      { from: "Paul Farley", to: { full: "Paul Farley", first: "Paul", last: "Farley" } },
      { from: "Michelle Paver", to: { full: "Michelle Paver", first: "Michelle", last: "Paver" } },
      { from: "David Peace", to: { full: "David Peace", first: "David", last: "Peace" } },
      { from: "Basharat Peer", to: { full: "Basharat Peer", first: "Basharat", last: "Peer" } },
      { from: "Mal Peet", to: { full: "Mal Peet", first: "Mal", last: "Peet" } },
      { from: "Harvey Pekar", to: { full: "Harvey Pekar", first: "Harvey", last: "Pekar" } },
      { from: "Penelope Fitzgerald", to: { full: "Penelope Fitzgerald", first: "Penelope", last: "Fitzgerald" } },
      { from: "Samuel Pepys", to: { full: "Samuel Pepys", first: "Samuel", last: "Pepys" } },
      { from: "Percy Bysshe Shelley", to: { full: "Percy Bysshe Shelley", first: "Percy Bysshe", last: "Shelley" } },
      { from: "Philip Hensher", to: { full: "Philip Hensher", first: "Philip", last: "Hensher" } },
      { from: "Piers Paul Read", to: { full: "Piers Paul Read", first: "Piers Paul", last: "Read" } },
      { from: "Piers Torday", to: { full: "Piers Torday", first: "Piers", last: "Torday" } },
      { from: "Harold Pinter", to: { full: "Harold Pinter", first: "Harold", last: "Pinter" } },
      { from: "Sylvia Plath", to: { full: "Sylvia Plath", first: "Sylvia", last: "Plath" } },

      { from: "Edgar Allan Poe", to: { full: "Edgar Allan Poe", first: "Edgar Allan", last: "Poe" } },
      { from: "Peter Porter", to: { full: "Peter Porter", first: "Peter", last: "Porter" } },
      { from: "Terry Pratchett", to: { full: "Terry Pratchett", first: "Terry", last: "Pratchett" } },
      { from: "Marcel Proust", to: { full: "Marcel Proust", first: "Marcel", last: "Proust" } },
      { from: "Philip Pullman", to: { full: "Philip Pullman", first: "Philip", last: "Pullman" } },
      { from: "Thomas Pynchon", to: { full: "Thomas Pynchon", first: "Thomas", last: "Pynchon" } },

      { from: "Jonathan Raban", to: { full: "Jonathan Raban", first: "Jonathan", last: "Raban" } },
      { from: "Rachel Cusk", to: { full: "Rachel Cusk", first: "Rachel", last: "Cusk" } },
      { from: "Ross Raisin", to: { full: "Ross Raisin", first: "Ross", last: "Raisin" } },
      { from: "Ian Rankin", to: { full: "Ian Rankin", first: "Ian", last: "Rankin" } },
      { from: "Arthur Ransome", to: { full: "Arthur Ransome", first: "Arthur", last: "Ransome" } },
      { from: "Redmond O'Hanlon", to: { full: "Redmond O'Hanlon", first: "Redmond", last: "O'Hanlon" } },
      { from: "David Remnick", to: { full: "David Remnick", first: "David", last: "Remnick" } },
      { from: "Ruth Rendell", to: { full: "Ruth Rendell", first: "Ruth", last: "Rendell" } },
      { from: "Reza Aslan", to: { full: "Reza Aslan", first: "Reza", last: "Aslan" } },
      { from: "Anne Rice", to: { full: "Anne Rice", first: "Anne", last: "Rice" } },
      { from: "Richard Flanagan", to: { full: "Richard Flanagan", first: "Richard", last: "Flanagan" } },
      { from: "Richard Ford", to: { full: "Richard Ford", first: "Richard", last: "Ford" } },
      { from: "Gwendoline Riley", to: { full: "Gwendoline Riley", first: "Gwendoline", last: "Riley" } },
      { from: "Robert Graves", to: { full: "Robert Graves", first: "Robert", last: "Graves" } },
      { from: "Marilynne Robinson", to: { full: "Marilynne Robinson", first: "Marilynne", last: "Robinson" } },
      { from: "Rose Tremain", to: { full: "Rose Tremain", first: "Rose", last: "Tremain" } },
      { from: "Michael Rosen", to: { full: "Michael Rosen", first: "Michael", last: "Rosen" } },
      { from: "Meg Rosoff", to: { full: "Meg Rosoff", first: "Meg", last: "Rosoff" } },
      { from: "Alex Ross", to: { full: "Alex Ross", first: "Alex", last: "Ross" } },
      { from: "Philip Roth", to: { full: "Philip Roth", first: "Philip", last: "Roth" } },
      { from: "JK Rowling", to: { full: "JK Rowling", first: "JK", last: "Rowling" } },
      { from: "Roxane Gay", to: { full: "Roxane Gay", first: "Roxane", last: "Gay" } },
      { from: "Arundhati Roy", to: { full: "Arundhati Roy", first: "Arundhati", last: "Roy" } },
      { from: "Salman Rushdie", to: { full: "Salman Rushdie", first: "Salman", last: "Rushdie" } },
      { from: "Russell Hoban", to: { full: "Russell Hoban", first: "Russell", last: "Hoban" } },

      { from: "Joe Sacco", to: { full: "Joe Sacco", first: "Joe", last: "Sacco" } },
      { from: "Jonathan Safran Foer", to: { full: "Jonathan Safran Foer", first: "Jonathan Safran", last: "Foer" } },
      { from: "JD Salinger", to: { full: "JD Salinger", first: "JD", last: "Salinger" } },
      { from: "Michael Sandel", to: { full: "Michael Sandel", first: "Michael", last: "Sandel" } },
      { from: "José Saramago", to: { full: "José Saramago", first: "José", last: "Saramago" } },
      { from: "Jean-Paul Sartre", to: { full: "Jean-Paul Sartre", first: "Jean-Paul", last: "Sartre" } },
      { from: "Siegfried Sassoon", to: { full: "Siegfried Sassoon", first: "Siegfried", last: "Sassoon" } },
      { from: "George Saunders", to: { full: "George Saunders", first: "George", last: "Saunders" } },
      { from: "Dorothy L Sayers", to: { full: "Dorothy L Sayers", first: "Dorothy L", last: "Sayers" } },
      { from: "Sir Walter Scott", to: { full: "Sir Walter Scott", title: "Sir", first: "Walter", last: "Scott" } },
      { from: "WG Sebald", to: { full: "WG Sebald", first: "WG", last: "Sebald" } },
      { from: "Will Self", to: { full: "Will Self", first: "Will", last: "Self" } },
      { from: "Maurice Sendak", to: { full: "Maurice Sendak", first: "Maurice", last: "Sendak" } },
      { from: "Dr Seuss", to: { full: "Dr Seuss", title: "Dr", last: "Seuss" } },
      { from: "William Shakespeare", to: { full: "William Shakespeare", first: "William", last: "Shakespeare" } },
      { from: "Shaun Tan", to: { full: "Shaun Tan", first: "Shaun", last: "Tan" } },
      { from: "Mary Shelley", to: { full: "Mary Shelley", first: "Mary", last: "Shelley" } },
      { from: "Carol Shields", to: { full: "Carol Shields", first: "Carol", last: "Shields" } },
      { from: "Lionel Shriver", to: { full: "Lionel Shriver", first: "Lionel", last: "Shriver" } },
      { from: "Alan Sillitoe", to: { full: "Alan Sillitoe", first: "Alan", last: "Sillitoe" } },
      { from: "Georges Simenon", to: { full: "Georges Simenon", first: "Georges", last: "Simenon" } },
      { from: "Posy Simmonds", to: { full: "Posy Simmonds", first: "Posy", last: "Simmonds" } },
      { from: "Francesca Simon", to: { full: "Francesca Simon", first: "Francesca", last: "Simon" } },
      { from: "Iain Sinclair", to: { full: "Iain Sinclair", first: "Iain", last: "Sinclair" } },
      { from: "Lemn Sissay", to: { full: "Lemn Sissay", first: "Lemn", last: "Sissay" } },
      { from: "Edith Sitwell", to: { full: "Edith Sitwell", first: "Edith", last: "Sitwell" } },
      { from: "Robert Skidelsky", to: { full: "Robert Skidelsky", first: "Robert", last: "Skidelsky" } },
      { from: "Jane Smiley", to: { full: "Jane Smiley", first: "Jane", last: "Smiley" } },
      { from: "Ali Smith", to: { full: "Ali Smith", first: "Ali", last: "Smith" } },
      { from: "Tom Rob Smith", to: { full: "Tom Rob Smith", first: "Tom Rob", last: "Smith" } },
      { from: "Wilbur Smith", to: { full: "Wilbur Smith", first: "Wilbur", last: "Smith" } },
      { from: "Zadie Smith", to: { full: "Zadie Smith", first: "Zadie", last: "Smith" } },
      { from: "Andrew Solomon", to: { full: "Andrew Solomon", first: "Andrew", last: "Solomon" } },
      { from: "Aleksandr Solzhenitsyn", to: { full: "Aleksandr Solzhenitsyn", first: "Aleksandr", last: "Solzhenitsyn" } },
      { from: "Wole Soyinka", to: { full: "Wole Soyinka", first: "Wole", last: "Soyinka" } },
      { from: "Muriel Spark", to: { full: "Muriel Spark", first: "Muriel", last: "Spark" } },
      { from: "Art Spiegelman", to: { full: "Art Spiegelman", first: "Art", last: "Spiegelman" } },
      { from: "Edward St Aubyn", to: { full: "Edward St Aubyn", first: "Edward", last: "St Aubyn" } },
      { from: "John Steinbeck", to: { full: "John Steinbeck", first: "John", last: "Steinbeck" } },
      { from: "Gloria Steinem", to: { full: "Gloria Steinem", first: "Gloria", last: "Steinem" } },
      { from: "Laurence Sterne", to: { full: "Laurence Sterne", first: "Laurence", last: "Sterne" } },
      { from: "Robert Louis Stevenson", to: { full: "Robert Louis Stevenson", first: "Robert Louis", last: "Stevenson" } },
      { from: "Kathryn Stockett", to: { full: "Kathryn Stockett", first: "Kathryn", last: "Stockett" } },
      { from: "Sue Townsend", to: { full: "Sue Townsend", first: "Sue", last: "Townsend" } },
      { from: "Graham Swift", to: { full: "Graham Swift", first: "Graham", last: "Swift" } },
      { from: "Jonathan Swift", to: { full: "Jonathan Swift", first: "Jonathan", last: "Swift" } },

      { from: "Nassim Nicholas Taleb", to: { full: "Nassim Nicholas Taleb", first: "Nassim Nicholas", last: "Taleb" } },
      { from: "Raymond Tallis", to: { full: "Raymond Tallis", first: "Raymond", last: "Tallis" } },
      { from: "Alfred Tennyson", to: { full: "Alfred Tennyson", first: "Alfred", last: "Tennyson" } },
      { from: "Studs Terkel", to: { full: "Studs Terkel", first: "Studs", last: "Terkel" } },
      { from: "Ngugi wa Thiong'o", to: { full: "Ngugi wa Thiong'o", first: "Ngugi", last: "wa Thiong'o" } },
      { from: "Dylan Thomas", to: { full: "Dylan Thomas", first: "Dylan", last: "Thomas" } },
      { from: "Hunter S Thompson", to: { full: "Hunter S Thompson", first: "Hunter S", last: "Thompson" } },
      { from: "Rupert Thomson", to: { full: "Rupert Thomson", first: "Rupert", last: "Thomson" } },
      { from: "Colm Tóibín", to: { full: "Colm Tóibín", first: "Colm", last: "Tóibín" } },
      { from: "JRR Tolkien", to: { full: "JRR Tolkien", first: "JRR", last: "Tolkien" } },
      { from: "Leo Tolstoy", to: { full: "Leo Tolstoy", first: "Leo", last: "Tolstoy" } },
      { from: "Tom McCarthy", to: { full: "Tom McCarthy", first: "Tom", last: "McCarthy" } },
      { from: "Claire Tomalin", to: { full: "Claire Tomalin", first: "Claire", last: "Tomalin" } },
      { from: "Justin Torres", to: { full: "Justin Torres", first: "Justin", last: "Torres" } },
      { from: "William Trevor", to: { full: "William Trevor", first: "William", last: "Trevor" } },
      { from: "Hugh Trevor-Roper", to: { full: "Hugh Trevor-Roper", first: "Hugh", last: "Trevor-Roper" } },
      { from: "Anthony Trollope", to: { full: "Anthony Trollope", first: "Anthony", last: "Trollope" } },
      { from: "TS Eliot", to: { full: "TS Eliot", first: "TS", last: "Eliot" } },
      { from: "Christos Tsiolkas", to: { full: "Christos Tsiolkas", first: "Christos", last: "Tsiolkas" } },
      { from: "Mark Twain", to: { full: "Mark Twain", first: "Mark", last: "Twain" } },

      { from: "David Uberti", to: { full: "David Uberti", first: "David", last: "Uberti" } },
      { from: "Barry Unsworth", to: { full: "Barry Unsworth", first: "Barry", last: "Unsworth" } },
      { from: "John Updike", to: { full: "John Updike", first: "John", last: "Updike" } },

      { from: "Mario Vargas Llosa", to: { full: "Mario Vargas Llosa", first: "Mario Vargas", last: "Llosa" } },
      { from: "Francois Marie Arouet de Voltaire", to: { full: "Francois Marie Arouet de Voltaire", first: "Francois Marie Arouet", last: "de Voltaire" } },
      { from: "Kurt Vonnegut", to: { full: "Kurt Vonnegut", first: "Kurt", last: "Vonnegut" } },

      { from: "Derek Walcott", to: { full: "Derek Walcott", first: "Derek", last: "Walcott" } },
      { from: "Alice Walker", to: { full: "Alice Walker", first: "Alice", last: "Walker" } },
      { from: "David Foster Wallace", to: { full: "David Foster Wallace", first: "David Foster", last: "Wallace" } },
      { from: "Natasha Walter", to: { full: "Natasha Walter", first: "Natasha", last: "Walter" } },
      { from: "Joseph Wambaugh", to: { full: "Joseph Wambaugh", first: "Joseph", last: "Wambaugh" } },
      { from: "Jesmyn Ward", to: { full: "Jesmyn Ward", first: "Jesmyn", last: "Ward" } },
      { from: "Alan Warner", to: { full: "Alan Warner", first: "Alan", last: "Warner" } },
      { from: "Sarah Waters", to: { full: "Sarah Waters", first: "Sarah", last: "Waters" } },
      { from: "Evelyn Waugh", to: { full: "Evelyn Waugh", first: "Evelyn", last: "Waugh" } },
      { from: "Fay Weldon", to: { full: "Fay Weldon", first: "Fay", last: "Weldon" } },
      { from: "HG Wells", to: { full: "HG Wells", first: "HG", last: "Wells" } },
      { from: "Irvine Welsh", to: { full: "Irvine Welsh", first: "Irvine", last: "Welsh" } },
      { from: "Edith Wharton", to: { full: "Edith Wharton", first: "Edith", last: "Wharton" } },
      { from: "Edmund White", to: { full: "Edmund White", first: "Edmund", last: "White" } },
      { from: "Oscar Wilde", to: { full: "Oscar Wilde", first: "Oscar", last: "Wilde" } },
      { from: "Hugo Williams", to: { full: "Hugo Williams", first: "Hugo", last: "Williams" } },
      { from: "Tennessee Williams", to: { full: "Tennessee Williams", first: "Tennessee", last: "Williams" } },
      { from: "Jacqueline Wilson", to: { full: "Jacqueline Wilson", first: "Jacqueline", last: "Wilson" } },
      { from: "Jeanette Winterson", to: { full: "Jeanette Winterson", first: "Jeanette", last: "Winterson" } },
      { from: "PG Wodehouse", to: { full: "PG Wodehouse", first: "PG", last: "Wodehouse" } },
      { from: "Naomi Wolf", to: { full: "Naomi Wolf", first: "Naomi", last: "Wolf" } },
      { from: "Tom Wolfe", to: { full: "Tom Wolfe", first: "Tom", last: "Wolfe" } },
      { from: "Mary Wollstonecraft", to: { full: "Mary Wollstonecraft", first: "Mary", last: "Wollstonecraft" } },
      { from: "Virginia Woolf", to: { full: "Virginia Woolf", first: "Virginia", last: "Woolf" } },
      { from: "William Wordsworth", to: { full: "William Wordsworth", first: "William", last: "Wordsworth" } },
      { from: "John Wyndham", to: { full: "John Wyndham", first: "John", last: "Wyndham" } },
      { from: "Diana Wynne Jones", to: { full: "Diana Wynne Jones", first: "Diana Wynne", last: "Jones" } },

      { from: "WB Yeats", to: { full: "WB Yeats", first: "WB", last: "Yeats" } },

      { from: "Slavoj Zizek", to: { full: "Slavoj Zizek", first: "Slavoj", last: "Zizek" } },
      { from: "Emile Zola", to: { full: "Emile Zola", first: "Emile", last: "Zola" } }
      ].each do |name|
        it "parses #{name[:from]}" do
          skip if name[:skip]
          parsed = Nomener.parse(name[:from])
          parse_hash = parsed.to_h
          parse_hash.each_pair do |k,v|
            unless (v.nil? || v.empty?)
              expect(v).to eq(name[:to][k]), "got from #{k} - #{v} not #{name[:to][k]}"
            end
          end
        end
      end

    end
  end